<a href="https://colab.research.google.com/github/srj1407/Data_Science_and_ML/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


In [38]:
scalar = torch.tensor(3)

In [39]:
scalar.ndim

0

In [40]:
scalar.item()

3

In [41]:
vector = torch.tensor([1, 2])

In [42]:
vector.ndim

1

In [43]:
vector.values

<function Tensor.values>

In [44]:
matrix = torch.tensor([[1, 2],
                      [3, 4]])

In [45]:
matrix.ndim

2

In [46]:
matrix.shape

torch.Size([2, 2])

In [47]:
matrix[0]

tensor([1, 2])

In [48]:
matrix[1, 1]

tensor(4)

In [49]:
matrix = torch.tensor([[[[1, 2],
                      [3, 4]]]])

In [50]:
matrix.shape

torch.Size([1, 1, 2, 2])

In [51]:
matrix[0][0]

tensor([[1, 2],
        [3, 4]])

In [52]:
matrix[0][0][1]

tensor([3, 4])

In [53]:
matrix.ndim

4

In [54]:
random_tensor = torch.rand((3, 4))

In [55]:
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.2055, 0.9824, 0.2295, 0.5451],
         [0.1879, 0.2669, 0.3605, 0.1476],
         [0.8553, 0.3267, 0.4835, 0.8707]]),
 2,
 torch.Size([3, 4]))

In [56]:
random_tensor = torch.rand((1, 1, 3, 4))

In [57]:
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[[[0.2900, 0.5132, 0.4462, 0.2266],
           [0.7428, 0.7579, 0.8767, 0.3706],
           [0.5892, 0.6867, 0.1693, 0.4429]]]]),
 4,
 torch.Size([1, 1, 3, 4]))

In [58]:
random_tensor = torch.rand(size = (255, 255, 3))

In [59]:
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[[0.4287, 0.1679, 0.7081],
          [0.5132, 0.8565, 0.3279],
          [0.6513, 0.2708, 0.2444],
          ...,
          [0.7126, 0.5922, 0.1499],
          [0.7820, 0.9289, 0.2214],
          [0.1088, 0.5535, 0.0220]],
 
         [[0.2906, 0.1858, 0.2043],
          [0.2618, 0.6116, 0.6183],
          [0.3209, 0.3962, 0.0228],
          ...,
          [0.1044, 0.2670, 0.9275],
          [0.7778, 0.7355, 0.3929],
          [0.2953, 0.4639, 0.3458]],
 
         [[0.4096, 0.1682, 0.7952],
          [0.7245, 0.8052, 0.3439],
          [0.9483, 0.4218, 0.9271],
          ...,
          [0.7592, 0.0403, 0.5403],
          [0.4225, 0.9735, 0.4735],
          [0.0187, 0.7404, 0.7730]],
 
         ...,
 
         [[0.3664, 0.5457, 0.5593],
          [0.9512, 0.0825, 0.1525],
          [0.1998, 0.1210, 0.7143],
          ...,
          [0.5029, 0.2189, 0.4813],
          [0.3987, 0.8582, 0.7613],
          [0.7628, 0.1043, 0.6140]],
 
         [[0.5490, 0.9507, 0.4388],
          [0

In [60]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [61]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [62]:
zeros*ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [63]:
zeros = torch.zeros(3, 1)
zeros

tensor([[0.],
        [0.],
        [0.]])

In [64]:
zeros*ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [65]:
zero_to_twenty = torch.arange(start = 0, end = 21, step = 1)
zero_to_twenty


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])

In [66]:
zeros = torch.zeros_like(zero_to_twenty)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
ones = torch.ones_like(zero_to_twenty)
ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [68]:
float_32_tensor = torch.tensor([2.0, 4.0, 6.0], dtype = None, device = None, requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([2., 4., 6.]), torch.float32)

In [69]:
float_16_tensor = torch.tensor([2.0, 4.0, 6.0], dtype = torch.float16, device = None, requires_grad=False)
float_16_tensor, float_16_tensor.dtype

(tensor([2., 4., 6.], dtype=torch.float16), torch.float16)

In [70]:
float_16_tensor = torch.tensor([2.0, 4.0, 6.0], dtype = torch.float16, device = 'cuda', requires_grad=False)
float_16_tensor, float_16_tensor.dtype, float_16_tensor.device

(tensor([2., 4., 6.], device='cuda:0', dtype=torch.float16),
 torch.float16,
 device(type='cuda', index=0))

In [71]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor, float_64_tensor.dtype, float_64_tensor.device

(tensor([2., 4., 6.], dtype=torch.float64), torch.float64, device(type='cpu'))

In [72]:
float_16_tensor*float_32_tensor

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [73]:
float_32_tensor*float_64_tensor

tensor([ 4., 16., 36.], dtype=torch.float64)

In [74]:
tensor = torch.tensor([1., 2., 3.])
tensor

tensor([1., 2., 3.])

In [75]:
tensor+10

tensor([11., 12., 13.])

In [76]:
tensor*10

tensor([10., 20., 30.])

In [77]:
tensor-10

tensor([-9., -8., -7.])

In [78]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [79]:
torch.add(tensor, 10), torch.mul(tensor, 10), torch.sub(tensor, 10), torch.div(tensor, 10)

(tensor([11., 12., 13.]),
 tensor([10., 20., 30.]),
 tensor([-9., -8., -7.]),
 tensor([0.1000, 0.2000, 0.3000]))

In [80]:
tensor = torch.tensor([1., 2., 3.])

In [81]:
tensor*tensor

tensor([1., 4., 9.])

In [82]:
tensor.shape

torch.Size([3])

In [83]:
tensor.matmul(tensor)

tensor(14.)

In [84]:
tensor @ tensor

tensor(14.)

In [85]:
tensor = torch.rand(1, 3)
tensor

tensor([[0.3028, 0.1572, 0.3860]])

In [86]:
tensor*tensor

tensor([[0.0917, 0.0247, 0.1490]])

In [87]:
tensor.matmul(tensor)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 1x3)

In [88]:
tensor = torch.rand(1000)

In [89]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value

CPU times: user 16.8 ms, sys: 0 ns, total: 16.8 ms
Wall time: 21.4 ms


tensor(325.6790)

In [90]:
%%time
value = tensor.matmul(tensor)
value

CPU times: user 67 µs, sys: 15 µs, total: 82 µs
Wall time: 87.3 µs


tensor(325.6794)

In [91]:
tensor = torch.rand(1, 3)
tensor

tensor([[0.3327, 0.2039, 0.7675]])

In [92]:
res = tensor.matmul(tensor.T)
res.shape

torch.Size([1, 1])

In [93]:
x = torch.tensor([1, 2, 3])
x.shape, x.dtype

(torch.Size([3]), torch.int64)

In [94]:
x.min(), torch.min(x)

(tensor(1), tensor(1))

In [95]:
x.max(), torch.max(x)

(tensor(3), tensor(3))

In [96]:
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(2.), tensor(2.))

In [97]:
torch.sum(x)

tensor(6)

In [98]:
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [99]:
x.argmax(), torch.argmax(x)

(tensor(2), tensor(2))

In [100]:
x=torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [102]:
y=x.reshape(1, 9)
y

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [104]:
y[0][1]=1
y, x

(tensor([[1., 1., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 1., 3., 4., 5., 6., 7., 8., 9.]))

In [107]:
z=x.view(3, 3)
z

tensor([[1., 1., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [109]:
z[1][1]=2
z, x, y

(tensor([[1., 1., 3.],
         [4., 2., 6.],
         [7., 8., 9.]]),
 tensor([1., 1., 3., 4., 2., 6., 7., 8., 9.]),
 tensor([[1., 1., 3., 4., 2., 6., 7., 8., 9.]]))

In [110]:
x.shape, y.shape

(torch.Size([9]), torch.Size([1, 9]))

In [113]:
w=y.squeeze()
w.shape

torch.Size([9])

In [118]:
x=w.unsqueeze(dim=1)
w, x, x.shape

(tensor([1., 1., 3., 4., 2., 6., 7., 8., 9.]),
 tensor([[1.],
         [1.],
         [3.],
         [4.],
         [2.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [121]:
y=x.unsqueeze(dim=1)
x, y, x.shape, y.shape

(tensor([[1.],
         [1.],
         [3.],
         [4.],
         [2.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([[[1.]],
 
         [[1.]],
 
         [[3.]],
 
         [[4.]],
 
         [[2.]],
 
         [[6.]],
 
         [[7.]],
 
         [[8.]],
 
         [[9.]]]),
 torch.Size([9, 1]),
 torch.Size([9, 1, 1]))

In [125]:
x=torch.rand(size = (1, 2, 3))
x

tensor([[[0.5696, 0.9082, 0.3533],
         [0.9996, 0.2607, 0.8269]]])

In [126]:
y=x.permute(2, 0, 1)

In [127]:
y

tensor([[[0.5696, 0.9996]],

        [[0.9082, 0.2607]],

        [[0.3533, 0.8269]]])

In [140]:
x=torch.arange(1., 10.).reshape(1, 3, 3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [131]:
x[0], x[0][1], x[0][1][2]

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([4., 5., 6.]),
 tensor(6.))

In [132]:
x[:, :, 1]

tensor([[2., 5., 8.]])

In [133]:
x[:, 1, :]

tensor([[4., 5., 6.]])

In [145]:
x[0][:][:][:][:][2]

tensor([7., 8., 9.])

In [156]:
x[:, :, 1]

tensor([[2., 5., 8.]])

In [157]:
import numpy as np
ar = np.arange(1., 10.)
ar

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [158]:
tsr = torch.from_numpy(ar)
tsr

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [159]:
ar=ar+1
ar, tsr

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [165]:
tsr2=torch.ones(10)
tsr2, tsr2.dtype

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), torch.float32)

In [162]:
ar2=tsr2.numpy()

In [166]:
ar2, ar2.dtype

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [167]:
tsr2=tsr2+1
tsr2, ar2

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [168]:
RANDOM_SEED = 42

In [170]:
torch.manual_seed(RANDOM_SEED)
tsr1=torch.rand(3, 4)
tsr2=torch.rand(3, 4)
tsr1, tsr2, tsr1==tsr2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [169]:
torch.manual_seed(RANDOM_SEED)
tsr1=torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
tsr2=torch.rand(3, 4)
tsr1, tsr2, tsr1==tsr2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [171]:
!nvidia-smi

Fri May  8 15:48:30 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   78C    P0             35W /   70W |     123MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [174]:
torch.cuda.is_available()

True

In [176]:
tsr1.device

device(type='cpu')

In [177]:
torch.cuda.device_count()

1